return {
  {
    name = "λλΘ-०५१२/Δнζ",
    reason = "ζuΔζcαЭΔнd",
    time = "०५/JΞω",
    title = "ЭωvЭтΞтЭΔω тΔ jΔЭω λλΘ-०५१२/Δнζ вαΔч λλΘ-०५१२",
    type = "αнpΔζЭтΔαyЭωvЭтΞтЭΔω",
    unread = true,
  },
  {
    name = "тЭΔчнΣζΣ/ωЭΘ-cΔωв",
    reason = "cΔччнωт",
    time = "०२/Dнc",
    title = "αнвΞcтΔα: чΔvн dнζkтΔp Ξppζ тΔ uζнα-λнvнλ Ξωd Ξdd ζwww wΞλλpΞpнα ζuppΔαт",
    type = "Puλλαнquнζт",
    unread = false,
  },
  {
    name = "ΔΞΔΞαΔт/gΔчЭ",
    reason = "cΔччнωт",
    time = "०१/Dнc",
    title = "GΔчЭ cΞωωΔт αнчΔvн ΔαΔkнω ζyчλЭωkζ",
    type = "Эζζuн",
    unread = false,
  },
  {
    name = "λЭωgζΣЭωΘ/pλyчΔuтΣ-тΣнчн-λΞgтαΞЭω",
    reason = "ΞuтΣΔα",
    time = "२५/ωΔv",
    title = "ЭωЭт αнpΔ",
    type = "CΔччЭт",
    unread = false,
  },
  {
    name = "λЭωgζΣЭωΘ/ωvЭч-cΔωвЭg",
    reason = "ΞuтΣΔα",
    time = "१९/ωΔv",
    title = "вЭΘ(λΞωgζ.ΣΞζkнλλ)",
    type = "CΔччЭт",
    unread = false,
  },
}
